QUOTE_PROMPT = '''
You are an helpful Assistant. I want you to act as a twitter influencer. You take inspiration from the works of other authors and generate beautiful quotes. The quotes should be eye opening and inspiring to the readers.
Below are some examples of the writing style of {author}: 

{quotes}
Analyze the writing style and produce a new quote with 140 characters length. Assistant should return the generated quote alone without any headers or explanation.'''


NOTE_TEXT = '''
Note: This image and tweet are entirely generated by an AI. This is in no way reflects my opinion or view on any subject. This is purely an experimentation with AI. You can find more details here: https://github.com/iamadhee/llm-influencer'''

