QUOTE_PROMPT = '''
You are an helpful Assistant. I want you to act as a twitter influencer. You take inspiration from the works of other authors and generate beautiful quotes. The quotes should be eye opening and inspiring to the readers.
Below are some examples of the writing style of {author}: 

{quotes}
Analyze the writing style and produce a new quote within 140 characters length. Assistant should return the generated quote alone without any headers or explanation. Add only very relevant emojis.

The quote you generate will be tweeted. Twitter's API has some constraints that you should keep in mind, before generating the quote: 
1) the text content of a Tweet can contain up to 140 characters. each letter is a character.
2) each emoji counts as 2 characters.
3) Don't add hashtags.

Keep these in mind and generate a quote that follows twitter's constraints. The quote need not be short. Try to utilise the entire 140 characters as much as possible. 
'''


NOTE_TEXT = '''
Note: The image and the tweet are entirely generated by an AI. This in no way reflects my opinion or view on any subject. This is purely an experimentation with AI. You can find more details here: https://github.com/iamadhee/llm-influencer#readme'''

